# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ola',
            table='ola',
        ),
    ]
