# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0005_auto_20170406_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.RemoveField(
            model_name='entity',
            name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='nomination.Entity'),
        ),
        migrations.AddField(
            model_name='person',
            name='ssn',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='nomination.Entity'),
        ),
    ]
