# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0006_auto_20170406_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^([0-9]){2}-([0-9]){5}$')])),
                ('career', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='ssn',
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^([0-9])+$')]),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
