# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0007_auto_20170406_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_id',
            new_name='ci',
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='nomination.Person'),
        ),
    ]
