# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0010_category_nominate'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nominate',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
