# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0012_auto_20170406_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'nominee',
            },
        ),
    ]
