# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0013_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomination.Category'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomination.Entity'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='nominations',
            field=models.IntegerField(default=0),
        ),
    ]
