# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomination', '0015_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='nominate',
            options={'verbose_name': 'Nomination', 'verbose_name_plural': 'Nominations'},
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name': 'Nominee', 'verbose_name_plural': 'Nominees'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': 'Winner', 'verbose_name_plural': 'Winners'},
        ),
        migrations.AlterUniqueTogether(
            name='nominate',
            unique_together=set([('nominator', 'nominee', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='nominee',
            unique_together=set([('entity', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together=set([('entity', 'category')]),
        ),
    ]
