# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habla', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=200)),
            ],
        ),
    ]
