# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chao',
        ),
        migrations.DeleteModel(
            name='Ola',
        ),
    ]
