# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_entity_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='profile_photo',
            field=models.ImageField(max_length=200, null=True, upload_to='profilePhoto/'),
        ),
    ]
