# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20170413_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='profile_photo',
            field=models.ImageField(max_length=200, null=True, upload_to='profilePhotos/'),
        ),
    ]
