# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20170415_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='inv',
            field=models.BooleanField(default=True),
        ),
    ]
