# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_category_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='inv',
        ),
    ]
