# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_nominate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominate',
            name='nomineeOpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Person'),
        ),
    ]
