# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_nominate_nomineeopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominate',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Entity'),
        ),
        migrations.AlterField(
            model_name='nominate',
            name='nomineeOpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Entity'),
        ),
    ]
