# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0009_auto_20170417_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nominate',
            unique_together=set([('nominator', 'nominee', 'nomineeOpt', 'category')]),
        ),
    ]
