# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20171031_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominate',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
