# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0016_nominee_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('extra', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Category')),
                ('nominator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Entity')),
                ('nomineeOpt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Entity')),
            ],
            options={
                'verbose_name': 'Voting',
                'db_table': 'vote',
                'verbose_name_plural': 'Voting',
            },
        ),
    ]
