# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='extra',
        ),
    ]
